       <div class="footer">
        <div class="contenedor">

            <div class="form__contacto">
              <form action="admin/enviar.php" method="post">
               <div class="linea__form">
                <label for="nombre" class="form__label">Nombre</label>
                <input type="text" class="form__input" name="nombre" id="nombre" required>
                </div>
               <div class="linea__form">
                <label for="empresa" class="form__label">Empresa</label>
                <input type="text" class="form__input" name="empresa" id="empresa" required>
                </div>                
                <div class="linea__form">
                <label for="mail" class="form__label">Mail</label>
                <input type="text" class="form__input" name="mail" id="mail" required>
                </div>
                <div class="linea__form">
                <label for="telefono" class="form__label">Teléfono</label>
                <input type="text" class="form__input" name="telefono" id="telefono">
                </div>
                <div class="linea__form">
                <label for="consulta" class="form__label">Consulta</label>
                <textarea name="consulta" id="consulta" class="form__textarea" required></textarea>
                </div>
                <input type="submit" value="Enviar" id="btnform">
            </form>
            </div>
            <div class="columna__footer">
                <div class="mapa">
                <div class="marco">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3281.044351070766!2d-58.39854309999999!3d-34.6788301!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bccc9444b1feef%3A0x38d70d02f858370c!2sJean%20Jaures%201864%2C%20B1822AIV%20Gerli%2C%20Provincia%20de%20Buenos%20Aires!5e0!3m2!1ses-419!2sar!4v1724120035362!5m2!1ses-419!2sar" width="400" height="370" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>


                </div>
                </div>
            </div>
        </div>
    </div>