<header>
   <section class="header2" id="header">
       <div class="contenedor_header2">
               <div class="logo_texto2">
           Integral Instrument
       </div>
        <div class="header__telefono2">
            <p class="telefono2">Tel. 4218-5675</p>
            <p class="telefono2">Cel. 11-5017-9931</p>
            <p class="mail2">info@integralinstrument.com.ar</p>
        </div>
        </div>
    </section>
</header>