       <div class="footer">
        <div class="contenedor">

            <div class="form__contacto">
              <form action="admin/enviar.php" method="post">
               <div class="linea__form">
                <label for="nombre" class="form__label">Nombre</label>
                <input type="text" class="form__input" name="nombre" id="nombre" required>
                </div>
               <div class="linea__form">
                <label for="empresa" class="form__label">Empresa</label>
                <input type="text" class="form__input" name="empresa" id="empresa" required>
                </div>                
                <div class="linea__form">
                <label for="mail" class="form__label">Mail</label>
                <input type="text" class="form__input" name="mail" id="mail" required>
                </div>
                <div class="linea__form">
                <label for="telefono" class="form__label">Teléfono</label>
                <input type="text" class="form__input" name="telefono" id="telefono">
                </div>
                <div class="linea__form">
                <label for="consulta" class="form__label">Consulta</label>
                <textarea name="consulta" id="consulta" class="form__textarea" required></textarea>
                </div>
                <input type="submit" value="Enviar" id="btnform">
            </form>
            </div>
            <div class="columna__footer">
                <div class="mapa">
                <div class="marco">
                   <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3281.190565930912!2d-58.38465018524937!3d-34.67513958044104!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x95bcccb783504dff%3A0x92b7c6514f0dc7f9!2sAv.+Hip%C3%B3lito+Yrigoyen+1577%2C+B1868EDE+Pi%C3%B1eiro%2C+Buenos+Aires!5e0!3m2!1ses-419!2sar!4v1474985664224" width="400" height="370" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>
                </div>
            </div>
        </div>
    </div>