<div class="contenedor_nav2">
    <nav class="navbar_home2 fixednav" id="navbar">
       <ul class="menu">
        <li class="menu__item"><a href="index.php" class="navbar_link2">:: La Empresa</a></li>
        <li class="menu__item"><a href="servicios.php" class="navbar_link2">:: Servicios</a></li>
        <li class="menu__item"><a href="obras.php" class="navbar_link2">:: Obras</a></li>
        <li class="menu__item"><a href="novedades.php" class="navbar_link2">:: Novedades</a> </li>  
        <li class="menu__item"><a href="contacto.php" class="navbar_link2">:: Contacto</a></li>
        </ul>
    </nav>
    <span class="icon-menu fixedicon" id="btnmenu"></span>
</div>